# Generated by Django 4.1.2 on 2022-10-10 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_driver_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
