# Generated by Django 4.1.2 on 2022-10-11 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_car_delete_driver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authentication',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
