# Generated by Django 4.1.2 on 2022-10-25 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time_zone',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
