# Generated by Django 4.1.2 on 2022-10-28 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_profile_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='url2audio',
            field=models.TextField(default='AudioBid'),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='worker_id',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
