# Generated by Django 4.1.2 on 2022-11-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_job_user_alter_job_worker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, 'AVAILABLE'), (1, 'INPROGRESS'), (2, 'COMPLETED'), (3, 'CANCELLED')], default=0),
        ),
    ]
