# Generated by Django 4.1.2 on 2022-11-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_reviewrating"),
    ]

    operations = [
        migrations.RemoveField(model_name="reviewrating", name="user",),
        migrations.AddField(
            model_name="reviewrating",
            name="creator_id",
            field=models.IntegerField(default="0"),
        ),
        migrations.AddField(
            model_name="reviewrating",
            name="worker_id",
            field=models.IntegerField(default="0"),
        ),
    ]
