# Generated by Django 4.1.2 on 2022-11-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_remove_reviewrating_user_reviewrating_creator_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="reviewrating", name="status",),
        migrations.AddField(
            model_name="reviewrating",
            name="job_id",
            field=models.IntegerField(default="-1"),
        ),
        migrations.AddField(
            model_name="reviewrating",
            name="number_of_ratings",
            field=models.IntegerField(default="0"),
        ),
        migrations.AlterField(
            model_name="reviewrating",
            name="creator_id",
            field=models.IntegerField(default="-1"),
        ),
        migrations.AlterField(
            model_name="reviewrating",
            name="worker_id",
            field=models.IntegerField(default="-1"),
        ),
    ]
