# Generated by Django 4.1.2 on 2022-11-16 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_remove_reviewrating_status_reviewrating_job_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewrating",
            name="job_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="users.job"
            ),
        ),
    ]
