# Generated by Django 4.1.2 on 2022-11-16 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_reviewrating_job_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewrating", old_name="job_id", new_name="job",
        ),
    ]
