# Generated by Django 4.1.2 on 2022-11-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_rename_job_id_reviewrating_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewrating",
            name="job",
            field=models.IntegerField(default="-1"),
        ),
    ]
