# Generated by Django 4.1.2 on 2022-11-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_alter_reviewrating_job"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewrating", old_name="job", new_name="job_id",
        ),
    ]
