# Generated by Django 4.1.2 on 2022-11-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_rename_job_reviewrating_job_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewrating",
            name="creator_id",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AlterField(
            model_name="reviewrating",
            name="worker_id",
            field=models.CharField(default="0", max_length=100),
        ),
    ]
