# Generated by Django 4.1.2 on 2022-11-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_reviewrating_creator_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewrating",
            name="job_id",
            field=models.BigIntegerField(default="-1"),
        ),
    ]
