# Generated by Django 4.1.2 on 2022-11-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_alter_reviewrating_job_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewrating",
            name="rating",
            field=models.FloatField(null=True),
        ),
    ]
