# Generated by Django 4.1.2 on 2022-11-18 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_comment"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="email",),
        migrations.RemoveField(model_name="comment", name="name",),
    ]
