# Generated by Django 4.1.2 on 2022-11-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_remove_comment_email_remove_comment_name"),
    ]

    operations = [
        migrations.RenameField(model_name="comment", old_name="post", new_name="job",),
    ]
