# Generated by Django 4.1.2 on 2022-11-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_rename_post_comment_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
