# Generated by Django 4.1.2 on 2022-11-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_job_transcript_alter_job_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="job", name="transcript",),
        migrations.RemoveField(model_name="reviewrating", name="number_of_ratings",),
        migrations.AddField(
            model_name="profile",
            name="number_of_ratings",
            field=models.IntegerField(default="0"),
        ),
        migrations.AddField(
            model_name="profile", name="rating", field=models.FloatField(default=0.0),
        ),
    ]
