# Generated by Django 4.1.2 on 2022-11-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='limit_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
    ]
