# Generated by Django 4.1.3 on 2022-11-24 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_job_limit_price'),
        ('users', '0028_remove_job_transcript_and_more'),
    ]

    operations = [
    ]
