# Generated by Django 4.1.3 on 2022-11-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_merge_20221123_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cron_date',
            field=models.DateTimeField(null=True),
        ),
    ]
