# Generated by Django 4.1.3 on 2022-11-24 07:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_job_cron_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
