# Generated by Django 4.1.2 on 2022-11-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, 'AVAILABLE'), (1, 'INPROGRESS'), (2, 'COMPLETED'), (3, 'INREVIEW')], default=0),
        ),
    ]
